name: Python Wheels

# TODO: Shrink this down to pushes to master, perhaps. During development, this
# needs to run more often to work out bugs.
on:
  - push
  
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.4
        env:
          CIBW_BUILD: "cp3{8,9,10,11}-*"
          CIBW_ARCHS_LINUX: "x86_64 aarch64"
          CIBW_ARCHS_MACOS: x86_64 arm64
        with:
           output-dir: wheelhouse
           
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
